### ISSUE TITLE
<< on properties doesn't persist

### ISSUE THREAD

**Issue by tpendragon** [samvera/active_fedora#768] opened 2015-04-14 22:35 UTC
We may not support <<, but right now it looks like it works and then doesn't persist.

``` ruby
class Test < ActiveFedora::Base
  property :title, :predicate => RDF::DC.title
end
t = Test.new
t.title << "Test"
t.title # => ["Test"]
t.save
t.title # => []
t.title += ["Test"]
t.title # => ["Test"]
t.save
t.title # => ["Test"]
```

**Comment by awead** [comment] 2015-04-15 12:09
There's a duplicate of this issue in #540. We also added a test that should still be pending.

**Comment by atz** [comment] 2017-06-02 00:32
Closing as duplicate.

**Closed by atz** 2017-06-02 00:32 UTC
